### ISSUE TITLE
Unusable keyboard on Windows 11 Pro build 22624 and instruction to manual uninstallation

### ISSUE THREAD

**Issue by PetrNebukin** [LuisYeah1234-hub/NativeLinux#6]
After installing on the real UEFI Windows-PC with above version, the keyboard failed when starting NativeLinux.

Manual removal instructions:
1. Restart the computer several times until the "Preparing Automatic Repair" label appears and the "Automatic Repair" blue screen appears.
2. On the blue screen, go to: Advanced options -> Troubleshoot -> Advanced options -> Command prompt
3.
```
cd \d C;\Windows\System32
rm nativelinux.exe
regedit
```
4. In Registry Editor click on HKEY_LOCAL_MACHINE, then File -> Load Hive -> Choose file C:\Windows\System32\config\SYSTEM -> Enter any name (example: mainsys) -> Go to ControlSet001\Control\Session Manager
5. Edit BootExecute from this:
```
autocheck autochk *
nativeshell

```
to this:
```
autocheck autochk *

```
6. Reboot and enjoy!

> [!NOTE]
> remove.reg and install.bat doesn't work in Windows PE, don't try it

@LuisYeah1234-hub write this instruction in README.md :)

**Comment by LuisYeah1234-hub** [comment]
Yeah will do!

**Comment by PetrNebukin** [comment]
> Yeah will do! But not right now
> And it for real done the same thing as Windows 2000 ._.

Close this issue later when this bug is fixed (or declared unfixable) ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by PetrNebukin** [comment]
> Yeah will do! But not right now
> And it for real done the same thing as Windows 2000 ._.

Close this issue later when this bug is fixed (or declared unfixable) ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by LuisYeah1234-hub** [comment]
Done putting your Instructions inside README. now for the fixing it would require some time. to figure out whats wrong

**Comment by PetrNebukin** [comment]
> If not if you could provide the iso to the build you're using and that nativelinux does not work on it would be good.

Bro, I'll in about 2-3 hours

**Comment by PetrNebukin** [comment]
2-3 hours, hehe. Sorry for not replying soon.

Build 22621: keyboard not working on physical ASUS Prime H510M-R based PC. When I replug-in keyboard, it lights up and turns off after 2 seconds.

**Comment by PetrNebukin** [comment]
> provide the iso to the build you're using and that nativelinux does not work on it would be good.

I'm searching for my ISO now, if I'll find it, will send

**Comment by LuisYeah1234-hub** [comment]
> 2-3 hours, hehe. Sorry for not replying soon.
> 
> Build 22621: keyboard not working on physical ASUS Prime H510M-R based PC. When I replug-in keyboard, it lights up and turns off after 2 seconds.

Probably its because of using a Desktop PC keyboard and the Native Mode is not detecting it. Gonna test a Desktop Keyboard with NativeLinux on real hardware and see what happens.

**Comment by LuisYeah1234-hub** [comment]
It's not because Windows 11 isn't supported. Desktop USB Keyboards are not getting detected at all that will be planned to resolve

**Comment by PetrNebukin** [comment]
> It's not because Windows 11 isn't supported. Desktop USB Keyboards are not getting detected at all that will be planned to resolve

I have a laptop with the same Win11 build, then I’ll see how it works with it and report back :)

**Comment by PetrNebukin** [comment]
> It's not because Windows 11 isn't supported. Desktop USB Keyboards are not getting detected at all that will be planned to resolve

I have a laptop with the same Win11 build, then I’ll see how it works with it and report back :)

**Comment by LuisYeah1234-hub** [comment]
![image](https://github.com/user-attachments/assets/ce794108-1980-49fe-a6fc-82f2070b299b)
Works in VMware. probably because of the hardcoded keyboard class

**Comment by PetrNebukin** [comment]
> Works in VMware. probably because of the hardcoded keyboard class

There may not be a solution to this problem yet, I'm closing the issue

**Comment by LuisYeah1234-hub** [comment]
I've implemented External keyboard support let me know if it fixes your issue
